export type RegistryComponent = {
  name: string;
  file: string | string[];
  type?: string;
  dependencies?: string[];
  registryDependencies?: string[];
  description?: string;
};

const REGISTRY_BASE_URL = "https://aomi.dev/r";

// Helper to create registry dependency URLs
const aomi = (name: string) => `${REGISTRY_BASE_URL}/${name}.json`;
const assistantUI = (name: string) => `https://r.assistant-ui.com/${name}.json`;

export const registry: RegistryComponent[] = [
  // === AOMI CUSTOM COMPONENTS ===
  {
    name: "aomi-theme",
    file: "themes/default.css",
    type: "registry:style",
    description:
      "Shadcn-compatible theme variables (light + dark) for Aomi components.",
  },
  {
    name: "aomi-widget",
    file: [
      "components/aomi-widget.tsx",
      "components/backend-aa-provisioner.tsx",
    ],
    dependencies: ["@aomi-labs/client", "@aomi-labs/react"],
    registryDependencies: [aomi("aomi-frame"), aomi("aomi-wallet-kit")],
    description:
      "Embeddable Aomi widget with tenant-scoped provider or wallet authentication.",
  },
  {
    name: "aomi-frame",
    file: "components/aomi-frame.tsx",
    dependencies: ["@aomi-labs/react"],
    registryDependencies: [
      // Theme (CSS variables required by all components)
      aomi("aomi-theme"),
      // Internal aomi components (customized)
      aomi("assistant-thread"),
      aomi("assistant-threadlist-sidebar"),
      aomi("aomi-wallet-kit"),
      aomi("control-bar"),
      aomi("runtime-tx-handler"),
      // shadcn primitives
      "separator",
      "breadcrumb",
      "sidebar",
    ],
    description: "Full assistant shell with thread list and runtime wiring.",
  },
  {
    name: "aomi-wallet-kit",
    file: [
      "lib/wallet-kit.ts",
      "lib/wallet-kit/index.ts",
      "lib/wallet-kit/context.tsx",
      "lib/wallet-kit/types.ts",
      "lib/wallet-kit/env.ts",
      "lib/wallet-kit/identity.ts",
      "lib/wallet-kit/wallet-utils.ts",
      "lib/wallet-kit/accounts.ts",
      "lib/wallet-kit/catalog/evm-connector-catalog.ts",
      "lib/wallet-kit/catalog/svm-wallet-catalog.ts",
      "lib/wallet-kit/catalog/wallet-branding.ts",
      "lib/wallet-kit/catalog/wallet-ids.ts",
      "lib/wallet-kit/config/AomiWalletKitProvider.tsx",
      "lib/wallet-kit/config/evm-connection-persistence.ts",
      "lib/wallet-kit/config/execution.ts",
      "lib/wallet-kit/config/index.ts",
      "lib/wallet-kit/config/provider-auth.ts",
      "lib/wallet-kit/config/types.ts",
      "lib/wallet-kit/providers/plugin-registry.ts",
      "lib/wallet-kit/execution/backend-aa-context.tsx",
      "lib/wallet-kit/execution/execution-runtime.ts",
      "lib/wallet-kit/execution/wallet-execution.ts",
      "lib/wallet-kit/full-testnet-config.ts",
      "lib/wallet-kit/full-testnet-wallet-routing.tsx",
      "lib/wallet-kit/network-preferences.tsx",
      "lib/wallet-kit/wallet-debug.ts",
      "lib/wallet-kit/account/types.ts",
      "lib/wallet-kit/account/disabled-runtime.ts",
      "lib/wallet-kit/account/aomi-backend-client.ts",
      "lib/wallet-kit/account/aomi-backend-runtime.ts",
      "lib/wallet-kit/account/sign-out.ts",
      "lib/wallet-kit/account/encoding.ts",
      "lib/wallet-kit/account/use-widget-session-provider.ts",
      "lib/wallet-kit/account/use-resolved-account-runtime.ts",
      "lib/wallet-kit/composer/AomiWalletKitComposer.tsx",
      "lib/wallet-kit/composer/build-identity.ts",
      "lib/wallet-kit/composer/build-wallet-kit-actions.ts",
      "lib/wallet-kit/composer/merge-wallet-rows.ts",
      "lib/wallet-kit/composer/types.ts",
      "lib/wallet-kit/runtime/evm/brands.ts",
      "lib/wallet-kit/runtime/evm/disabled-runtime.ts",
      "lib/wallet-kit/runtime/evm/disconnect-plan.ts",
      "lib/wallet-kit/runtime/evm/provider.tsx",
      "lib/wallet-kit/runtime/evm/registry-source.ts",
      "lib/wallet-kit/runtime/evm/safe-hooks.ts",
      "lib/wallet-kit/runtime/evm/wallet-runtime.ts",
      "lib/wallet-kit/registry/identity-grace.ts",
      "lib/wallet-kit/registry/use-wallet-registry.ts",
      "lib/wallet-kit/catalog/svm-networks.ts",
      "lib/wallet-kit/runtime/svm/transactions.ts",
      "lib/wallet-kit/runtime/svm/registry-source.ts",
      "lib/wallet-kit/runtime/svm/wallet-runtime.ts",
      "lib/wallet-kit/registry/types.ts",
      "lib/wallet-kit/registry/reducer.ts",
      "lib/wallet-kit/registry/policy.ts",
      "lib/wallet-kit/registry/commands.ts",
      "lib/wallet-kit/registry/persistence.ts",
      "lib/wallet-kit/registry/store.ts",
      "lib/wallet-kit/registry/selectors.ts",
      "lib/wallet-kit/use-wallet-activation-guard.ts",
      "lib/wallet-identity.ts",
    ],
    dependencies: [
      "@aomi-labs/client",
      "@aomi-labs/react",
      "@solana/wallet-adapter-react",
      "@solana/wallet-standard-wallet-adapter-react",
      "@solana/web3.js",
      "@tanstack/react-query",
      "viem",
      "wagmi",
    ],
    description:
      "Generic Aomi wallet kit context. Identity → UserState sync is mounted automatically by AomiWalletKitContextProvider.",
  },
  {
    name: "control-bar",
    file: [
      "components/control-bar/index.tsx",
      "components/control-bar/model-select.tsx",
      "components/control-bar/model-metadata.ts",
      "components/control-bar/app-metadata.ts",
      "components/control-bar/app-select.tsx",
      "components/control-bar/api-key-input.tsx",
      "components/control-bar/connect-button.tsx",
      "components/control-bar/network-select.tsx",
      "components/control-bar/secret-input.tsx",
      "components/control-bar/payment-required-gate.tsx",
      "components/control-bar/dual-wallet-bar.tsx",
      "components/control-bar/account-menu.tsx",
      "components/control-bar/account-menu-types.ts",
      "components/control-bar/disconnect-confirm-dialog.tsx",
      "components/control-bar/wallet-picker.tsx",
      "components/control-bar/wallet-account-model.ts",
      "components/control-bar/wallet-picker-context.tsx",
      "components/control-bar/wallet-icon-slot.tsx",
      "components/ui/modal-backdrop.tsx",
      "components/icons/index.ts",
      "components/icons/auto-mode.tsx",
      "components/icons/app-map.tsx",
      "components/icons/vendor-map.tsx",
      "components/icons/chain-map.tsx",
      "components/icons/wallet-map.tsx",
      "components/icons/apps/index.tsx",
      "components/icons/vendors/index.tsx",
      "components/icons/chains/index.tsx",
      "components/icons/wallets/index.tsx",
      "lib/wallet-kit.ts",
      "lib/wallet-kit/accounts.ts",
      "lib/wallet-kit/network-preferences.tsx",
      "lib/wallet-kit/catalog/svm-networks.ts",
      "lib/wallet-identity.ts",
    ],
    dependencies: [
      "@aomi-labs/client",
      "@aomi-labs/react",
      "lucide-react",
      "wagmi",
    ],
    registryDependencies: [
      aomi("aomi-wallet-kit"),
      "button",
      "popover",
      "command",
      "dialog",
      "input",
      "label",
    ],
    description:
      "Control bar with model/App selectors, API key input, and wallet connect.",
  },
  {
    name: "assistant-thread",
    file: [
      "components/assistant-ui/thread.tsx",
      "components/assistant-ui/thread-loading.ts",
      "components/assistant-ui/working-trace.tsx",
      "components/assistant-ui/working-trace-rows.tsx",
      "components/assistant-ui/working-agent.tsx",
      "components/assistant-ui/tool-interpreter.ts",
      "components/assistant-ui/tool-interpreter/index.ts",
      "components/assistant-ui/tool-interpreter/types.ts",
      "components/assistant-ui/tool-interpreter/unwrap.ts",
      "components/assistant-ui/tool-interpreter/normalize.ts",
      "components/assistant-ui/tool-interpreter/pipeline.ts",
      "components/assistant-ui/tool-interpreter/families/simple.ts",
      "components/assistant-ui/tool-interpreter/families/evm-call.ts",
      "components/assistant-ui/tool-interpreter/families/evm-tx.ts",
      "components/assistant-ui/tool-interpreter/families/svm.ts",
      "components/assistant-ui/tool-interpreter/families/svm-tx.ts",
      "components/assistant-ui/tool-interpreter/families/jupiter.ts",
      "components/assistant-ui/tool-interpreter/families/lifi.ts",
      "components/assistant-ui/tool-interpreter/families/task.ts",
      "components/assistant-ui/tool-interpreter/present/index.ts",
      "components/assistant-ui/tool-interpreter/present/chips.ts",
      "components/assistant-ui/tool-interpreter/present/descriptors.ts",
      "components/assistant-ui/tool-interpreter/present/fallback.ts",
      "components/assistant-ui/tool-registry.ts",
      "components/icons/chain-map.tsx",
      "components/icons/chains/index.tsx",
    ],
    dependencies: [
      "@aomi-labs/react",
      "@assistant-ui/react@~0.11.28",
      "@assistant-ui/react-markdown@~0.11.1",
      "lucide-react",
      "motion",
      "remark-gfm",
    ],
    registryDependencies: [
      // From assistant-ui (unchanged)
      assistantUI("markdown-text"),
      assistantUI("tooltip-icon-button"),
      // Attachment: our own version compatible with @assistant-ui/react 0.11.x
      aomi("attachment"),
      // Internal aomi components (customized)
      aomi("assistant-tool-fallback"),
      // shadcn primitives
      "button",
      "skeleton",
    ],
    description: "Chat surface built on @assistant-ui primitives.",
  },
  {
    name: "assistant-thread-list",
    file: "components/assistant-ui/thread-list.tsx",
    dependencies: ["@assistant-ui/react@~0.11.28", "lucide-react"],
    registryDependencies: [
      aomi("aomi-wallet-kit"),
      assistantUI("tooltip-icon-button"),
      "button",
      "dialog",
      "skeleton",
    ],
    description: "Thread list wrapper wired to runtime adapter.",
  },
  {
    name: "assistant-threadlist-sidebar",
    file: [
      "components/assistant-ui/threadlist-sidebar.tsx",
      "components/aomi-logo.tsx",
      "components/aomi-mark.tsx",
    ],
    dependencies: ["lucide-react"],
    registryDependencies: [aomi("assistant-thread-list"), "sidebar"],
    description: "Sidebar shell for thread navigation and wallet footer slot.",
  },

  {
    name: "assistant-tool-fallback",
    file: "components/assistant-ui/tool-fallback.tsx",
    dependencies: ["@assistant-ui/react@~0.11.28", "lucide-react"],
    registryDependencies: ["button"],
    description: "Fallback renderer for assistant tool calls.",
  },
  {
    name: "attachment",
    file: "components/assistant-ui/attachment.tsx",
    dependencies: [
      "@assistant-ui/react@~0.11.28",
      "@aomi-labs/react",
      "lucide-react",
      "zustand",
    ],
    registryDependencies: [
      assistantUI("tooltip-icon-button"),
      "tooltip",
      "dialog",
      "avatar",
    ],
    description:
      "Attachment renderer compatible with @assistant-ui/react 0.11.x.",
  },
  {
    name: "notification",
    file: [
      "components/ui/notification.tsx",
      "components/ui/notification-icon.tsx",
    ],
    dependencies: ["@aomi-labs/react", "sonner"],
    registryDependencies: [aomi("sonner")],
    description:
      "Notification toaster wired to the runtime notification store.",
  },
  {
    name: "sonner",
    file: "components/ui/sonner.tsx",
    dependencies: ["sonner"],
    description: "Shadcn wrapper for Sonner toasts.",
  },
  {
    name: "runtime-tx-handler",
    file: "components/runtime-tx-handler.tsx",
    dependencies: ["@aomi-labs/react", "lucide-react"],
    registryDependencies: [aomi("aomi-wallet-kit"), "button", "dialog"],
    description:
      "Executes wallet transaction and EIP-712 signing requests from the AI backend through the active wallet kit.",
  },
  {
    name: "aomi-para-provider",
    file: [
      "lib/wallet-kit/providers/para/index.ts",
      "lib/wallet-kit/providers/para/para-brand.ts",
      "lib/wallet-kit/providers/para/para-plugin.tsx",
      "lib/wallet-kit/providers/para/ParaPluginProvider.tsx",
      "lib/wallet-kit/providers/para/para-evm-runtime-provider.tsx",
      "lib/wallet-kit/providers/para/para-message-signing.ts",
      "lib/wallet-kit/providers/para/para-auth.ts",
      "lib/wallet-kit/providers/para/para-embedded-wallet.ts",
      "lib/wallet-kit/providers/para/widget-auth.ts",
      "lib/wallet-kit/registry/use-wallet-registry.ts",
      "lib/wallet-kit/runtime/evm/registry-source.ts",
      "lib/wallet-kit/runtime/evm/provider.tsx",
      "lib/wallet-kit/runtime/evm/wallet-runtime.ts",
      "lib/wallet-kit/providers/sources/embedded-session-source.ts",
      "lib/wallet-kit/providers/para/sources/para-session-source.ts",
      "lib/wallet-kit/runtime/svm/registry-source.ts",
      "lib/wallet-kit/runtime/evm/disconnect-plan.ts",
      "lib/wallet-kit/registry/identity-grace.ts",
      "lib/wallet-kit/full-testnet-config.ts",
      "lib/wallet-kit/full-testnet-wallet-routing.tsx",
      "lib/wallet-kit/network-preferences.tsx",
      "lib/wallet-kit/runtime/evm/safe-hooks.ts",
      "lib/wallet-kit/runtime/evm/brands.ts",
      "lib/wallet-kit/catalog/evm-connector-catalog.ts",
      "lib/wallet-kit/catalog/wallet-ids.ts",
      "lib/wallet-kit/catalog/svm-networks.ts",
      "lib/wallet-kit/execution/wallet-execution.ts",
    ],
    dependencies: [
      "@aomi-labs/client",
      "@aomi-labs/react",
      "@getpara/react-sdk",
      "@getpara/wagmi-v2-connector",
      "@solana/wallet-adapter-react",
      "@solana/web3.js",
      "@tanstack/react-query",
      "viem",
      "wagmi",
    ],
    registryDependencies: [aomi("aomi-wallet-kit")],
    description:
      "Para-backed Aomi wallet kit provider with the existing Aomi AA path.",
  },
  {
    name: "aomi-privy-provider",
    file: [
      "lib/wallet-kit/providers/privy/index.ts",
      "lib/wallet-kit/providers/privy/PrivyPluginProvider.tsx",
      "lib/wallet-kit/providers/privy/PrivyProvider.tsx",
      "lib/wallet-kit/providers/privy/privy-auth.ts",
      "lib/wallet-kit/providers/privy/privy-execution.ts",
      "lib/wallet-kit/providers/privy/privy-delegation-context.ts",
      "lib/wallet-kit/providers/privy/privy-delegation.tsx",
      "lib/wallet-kit/providers/privy/privy-plugin.tsx",
      "lib/wallet-kit/providers/privy/privy-svm.ts",
      "lib/wallet-kit/providers/privy/privy.tsx",
      "lib/wallet-kit/providers/privy/widget-auth.ts",
      "lib/wallet-kit/providers/sources/embedded-session-source.ts",
      "lib/wallet-kit/catalog/evm-connector-catalog.ts",
      "lib/wallet-kit/catalog/wallet-ids.ts",
      "lib/wallet-kit/runtime/evm/safe-hooks.ts",
    ],
    dependencies: [
      "@aomi-labs/react",
      "@privy-io/react-auth",
      "@privy-io/wagmi",
      "@solana/web3.js",
      "@tanstack/react-query",
      "viem",
      "wagmi",
    ],
    registryDependencies: [aomi("aomi-wallet-kit")],
    description:
      "Privy-backed Aomi wallet kit provider using Privy's hosted smart wallets (EVM 4337) and Privy's embedded Solana wallets. Bundler, paymaster, and AA implementation are configured in the integrator's Privy dashboard.",
  },
  // === SHADCN UI PRIMITIVES ===
  {
    name: "button",
    file: "components/ui/button.tsx",
    dependencies: ["radix-ui", "class-variance-authority"],
    description: "Displays a button or a component that looks like a button.",
  },
  {
    name: "input",
    file: "components/ui/input.tsx",
    dependencies: [],
    description:
      "Displays a form input field or a component that looks like an input field.",
  },
  {
    name: "label",
    file: "components/ui/label.tsx",
    dependencies: ["radix-ui"],
    description: "Renders an accessible label associated with controls.",
  },
  {
    name: "card",
    file: "components/ui/card.tsx",
    dependencies: [],
    description: "Displays a card with header, content, and footer.",
  },
  {
    name: "badge",
    file: "components/ui/badge.tsx",
    dependencies: ["class-variance-authority"],
    description: "Displays a badge or a component that looks like a badge.",
  },
  {
    name: "avatar",
    file: "components/ui/avatar.tsx",
    dependencies: ["radix-ui"],
    description: "An image element with a fallback for representing the user.",
  },
  {
    name: "skeleton",
    file: "components/ui/skeleton.tsx",
    dependencies: [],
    description: "Use to show a placeholder while content is loading.",
  },
  {
    name: "tooltip",
    file: "components/ui/tooltip.tsx",
    dependencies: ["@radix-ui/react-tooltip"],
    description:
      "A popup that displays information related to an element when the element receives keyboard focus or the mouse hovers over it.",
  },
  {
    name: "separator",
    file: "components/ui/separator.tsx",
    dependencies: ["@radix-ui/react-separator"],
    description: "Visually or semantically separates content.",
  },
  {
    name: "breadcrumb",
    file: "components/ui/breadcrumb.tsx",
    dependencies: ["@radix-ui/react-slot"],
    description:
      "Displays the path to the current resource using a hierarchy of links.",
  },
  {
    name: "sidebar",
    file: "components/ui/sidebar.tsx",
    dependencies: ["@radix-ui/react-slot", "class-variance-authority"],
    description: "Displays a sidebar navigation component.",
  },
  {
    name: "dialog",
    file: "components/ui/dialog.tsx",
    dependencies: ["radix-ui", "lucide-react"],
    registryDependencies: ["button"],
    description:
      "A window overlaid on either the primary window or another dialog window.",
  },
  {
    name: "sheet",
    file: "components/ui/sheet.tsx",
    dependencies: ["radix-ui", "lucide-react"],
    description:
      "Extends the Dialog component to display content that complements the main content of the screen.",
  },
  {
    name: "collapsible",
    file: "components/ui/collapsible.tsx",
    dependencies: ["@radix-ui/react-collapsible"],
    description: "An interactive component which expands/collapses a panel.",
  },
  {
    name: "command",
    file: "components/ui/command.tsx",
    dependencies: ["@radix-ui/react-dialog", "cmdk", "lucide-react"],
    registryDependencies: ["dialog"],
    description: "Fast, composable, unstyled command menu for React.",
  },
  {
    name: "popover",
    file: "components/ui/popover.tsx",
    dependencies: ["radix-ui"],
    description: "Displays rich content in a portal, triggered by a button.",
  },
  {
    name: "alert",
    file: "components/ui/alert.tsx",
    dependencies: ["class-variance-authority"],
    description: "Displays a callout for user attention.",
  },
  {
    name: "accordion",
    file: "components/ui/accordion.tsx",
    dependencies: ["@radix-ui/react-accordion", "lucide-react"],
    description:
      "A vertically stacked set of interactive headings that each reveal a section of content.",
  },
  {
    name: "drawer",
    file: "components/ui/drawer.tsx",
    dependencies: ["vaul"],
    description:
      "A drawer component for mobile navigation menus and similar interfaces.",
  },
];
